// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiringManagementSystem.Classes;

#nullable disable

namespace WiringManagementSystem.Migrations
{
    [DbContext(typeof(WMContext))]
    partial class WMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WiringManagementSystem.Classes.Device", b =>
                {
                    b.Property<string>("DeviceID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RackID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceID");

                    b.HasIndex("RackID");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceID = "PODA",
                            DeviceName = "Pod A",
                            RackID = "RK01",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODB",
                            DeviceName = "Pod B",
                            RackID = "RK01",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODC",
                            DeviceName = "Pod C",
                            RackID = "RK01",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODD",
                            DeviceName = "Pod D",
                            RackID = "RK01",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "RT00",
                            DeviceName = "Cisco 1900 Series Router - Rack 1",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW00",
                            DeviceName = "Catalyst 2900 Plus Series Switch - Rack 1",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "FRWA",
                            DeviceName = "ASA 5505 Series Firewall - Bloc A",
                            RackID = "RK01",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWB",
                            DeviceName = "ASA 5505 Series Firewall - Bloc B",
                            RackID = "RK01",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWC",
                            DeviceName = "ASA 5505 Series Firewall - Bloc C",
                            RackID = "RK01",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWD",
                            DeviceName = "ASA 5505 Series Firewall - Bloc D",
                            RackID = "RK01",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "RT01",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT02",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT03",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW01",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW02",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW03",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODA",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT04",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT05",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT06",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW04",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW05",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW06",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODB",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT07",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT08",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT09",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW07",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW08",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW09",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODC",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT10",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT11",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT12",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW10",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW11",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW12",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODD",
                            RackID = "RK01",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "PODE",
                            DeviceName = "Pod E",
                            RackID = "RK02",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODF",
                            DeviceName = "Pod F",
                            RackID = "RK02",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODG",
                            DeviceName = "Pod G",
                            RackID = "RK02",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODH",
                            DeviceName = "Pod H",
                            RackID = "RK02",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "RT13",
                            DeviceName = "Cisco 1900 Series Router - Rack 2",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW13",
                            DeviceName = "Catalyst 2900 Plus Series Switch - Rack 2",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "FRWE",
                            DeviceName = "ASA 5505 Series Firewall - Bloc E",
                            RackID = "RK02",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWF",
                            DeviceName = "ASA 5505 Series Firewall - Bloc F",
                            RackID = "RK02",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWG",
                            DeviceName = "ASA 5505 Series Firewall - Bloc G",
                            RackID = "RK02",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWH",
                            DeviceName = "ASA 5505 Series Firewall - Bloc H",
                            RackID = "RK02",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "RT14",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT15",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT16",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW14",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW15",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW16",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODE",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT17",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT18",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT19",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW17",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW18",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW19",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODF",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT20",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT21",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT22",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW20",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW21",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW22",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODG",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT23",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT24",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT25",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW23",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW24",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW25",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODH",
                            RackID = "RK02",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SRVMGMT",
                            DeviceName = "Management Server",
                            RackID = "RK03",
                            Type = 0
                        },
                        new
                        {
                            DeviceID = "SRV01",
                            DeviceName = "Host 1 Server",
                            RackID = "RK03",
                            Type = 0
                        },
                        new
                        {
                            DeviceID = "SRV02",
                            DeviceName = "Host 2 Server",
                            RackID = "RK03",
                            Type = 0
                        },
                        new
                        {
                            DeviceID = "SWMGMT",
                            DeviceName = "Management Switch",
                            RackID = "RK03",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SWCLST",
                            DeviceName = "Cluster Switch",
                            RackID = "RK03",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SWCTRL",
                            DeviceName = "NL Control Switch",
                            RackID = "RK03",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SRVBCK",
                            DeviceName = "Backup Server",
                            RackID = "RK03",
                            Type = 0
                        },
                        new
                        {
                            DeviceID = "PODI",
                            DeviceName = "Pod I",
                            RackID = "RK04",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODJ",
                            DeviceName = "Pod J",
                            RackID = "RK04",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODK",
                            DeviceName = "Pod K",
                            RackID = "RK04",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODL",
                            DeviceName = "Pod L",
                            RackID = "RK04",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "RT26",
                            DeviceName = "Cisco 1900 Series Router - Rack 4",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW26",
                            DeviceName = "Catalyst 2900 Plus Series Switch - Rack 4",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "FRWI",
                            DeviceName = "ASA 5505 Series Firewall - Bloc I",
                            RackID = "RK04",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWJ",
                            DeviceName = "ASA 5505 Series Firewall - Bloc J",
                            RackID = "RK04",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWK",
                            DeviceName = "ASA 5505 Series Firewall - Bloc K",
                            RackID = "RK04",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWL",
                            DeviceName = "ASA 5505 Series Firewall - Bloc L",
                            RackID = "RK04",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "RT27",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT28",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT29",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW27",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW28",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW29",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODI",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT30",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT31",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT32",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW30",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW31",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW32",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODJ",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT33",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT34",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT35",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW33",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW34",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW35",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODK",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT36",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT37",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT38",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW36",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW37",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW38",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODL",
                            RackID = "RK04",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "PODM",
                            DeviceName = "Pod M",
                            RackID = "RK05",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODN",
                            DeviceName = "Pod N",
                            RackID = "RK05",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODO",
                            DeviceName = "Pod O",
                            RackID = "RK05",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "PODP",
                            DeviceName = "Pod P",
                            RackID = "RK05",
                            Type = 5
                        },
                        new
                        {
                            DeviceID = "RT39",
                            DeviceName = "Cisco 1900 Series Router - Rack 5",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW39",
                            DeviceName = "Catalyst 2900 Plus Series Switch - Rack 5",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "FRWM",
                            DeviceName = "ASA 5505 Series Firewall - Bloc M",
                            RackID = "RK05",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWN",
                            DeviceName = "ASA 5505 Series Firewall - Bloc N",
                            RackID = "RK05",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWO",
                            DeviceName = "ASA 5505 Series Firewall - Bloc O",
                            RackID = "RK05",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "FRWP",
                            DeviceName = "ASA 5505 Series Firewall - Bloc P",
                            RackID = "RK05",
                            Type = 3
                        },
                        new
                        {
                            DeviceID = "RT40",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT41",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT42",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW40",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW41",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW42",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODM",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT43",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT44",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT45",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW43",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW44",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW45",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODN",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT46",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT47",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT48",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW46",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW47",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW48",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODO",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "RT49",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT50",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "RT51",
                            DeviceName = "Cisco 1900 Series Router",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 2
                        },
                        new
                        {
                            DeviceID = "SW49",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW50",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 1
                        },
                        new
                        {
                            DeviceID = "SW51",
                            DeviceName = "Catalyst 2900 Plus Series Switch",
                            PodID = "PODP",
                            RackID = "RK05",
                            Type = 1
                        });
                });

            modelBuilder.Entity("WiringManagementSystem.Classes.Rack", b =>
                {
                    b.Property<string>("RackID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DevicesID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RackID");

                    b.ToTable("Racks");

                    b.HasData(
                        new
                        {
                            RackID = "RK01",
                            RackName = "Rack 1"
                        },
                        new
                        {
                            RackID = "RK02",
                            RackName = "Rack 2"
                        },
                        new
                        {
                            RackID = "RK03",
                            RackName = "Rack 3"
                        },
                        new
                        {
                            RackID = "RK04",
                            RackName = "Rack 4"
                        },
                        new
                        {
                            RackID = "RK05",
                            RackName = "Rack 5"
                        },
                        new
                        {
                            RackID = "RK06",
                            RackName = "Rack 6"
                        });
                });

            modelBuilder.Entity("WiringManagementSystem.Classes.Device", b =>
                {
                    b.HasOne("WiringManagementSystem.Classes.Rack", null)
                        .WithMany("Devices")
                        .HasForeignKey("RackID");
                });

            modelBuilder.Entity("WiringManagementSystem.Classes.Rack", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
